### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by ghost** [jpsingleton/Raspberry-Pi-Electricity-Monitor#1]
Is it possible to show graphs if logger records the data in a mysql database instead of csv ?

**Comment by jpsingleton** [comment]
It's certainly possible to log to mysql, PostgreSQL, SQLite, CouchDB or something like RRDtool instead of flat files. However, I'll probably look at integrating with http://emoncms.org/ instead and just pump the data into that. It appears to use mysql and redis for data storage.

There seem to be multiple projects for it:
- https://github.com/emoncms/emoncms
- https://github.com/emoncms/emonview
- https://github.com/emonhub/emonhub
